version: '3.1'
services:
  notebooks:
   image: jupyter/datascience-notebook:python-3.8.4
   ports:
     - "8888:8888"
   volumes: 
     - ./:/home/jovyan/
   command: bash -c "pip install -r requirements.txt && jupyter-notebook"
